# Generated by Django 4.0.4 on 2022-04-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(max_length=250),
        ),
    ]
