# Generated by Django 4.0.4 on 2022-05-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_comment_options_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_date',)},
        ),
    ]
